// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: grpc/api/echelon/v1/scanner.proto

package echelonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя с расширением .json, .yaml или .yml. Если имя пустое,
	// сервер попытается определить формат по содержимому.
	SourceName    string `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_grpc_api_echelon_v1_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_echelon_v1_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_echelon_v1_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ScanRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_grpc_api_echelon_v1_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_echelon_v1_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_echelon_v1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type Finding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Rule           string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_grpc_api_echelon_v1_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_echelon_v1_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_grpc_api_echelon_v1_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Finding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

var File_grpc_api_echelon_v1_scanner_proto protoreflect.FileDescriptor

const file_grpc_api_echelon_v1_scanner_proto_rawDesc = "" +
	"\n" +
	"!grpc/api/echelon/v1/scanner.proto\x12\n" +
	"echelon.v1\"H\n" +
	"\vScanRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"?\n" +
	"\fScanResponse\x12/\n" +
	"\bfindings\x18\x01 \x03(\v2\x13.echelon.v1.FindingR\bfindings\"\x8f\x01\n" +
	"\aFinding\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation2K\n" +
	"\x0eScannerService\x129\n" +
	"\x04Scan\x12\x17.echelon.v1.ScanRequest\x1a\x18.echelon.v1.ScanResponseB/Z-echelon-utility/grpc/api/echelon/v1;echelonv1b\x06proto3"

var (
	file_grpc_api_echelon_v1_scanner_proto_rawDescOnce sync.Once
	file_grpc_api_echelon_v1_scanner_proto_rawDescData []byte
)

func file_grpc_api_echelon_v1_scanner_proto_rawDescGZIP() []byte {
	file_grpc_api_echelon_v1_scanner_proto_rawDescOnce.Do(func() {
		file_grpc_api_echelon_v1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_api_echelon_v1_scanner_proto_rawDesc), len(file_grpc_api_echelon_v1_scanner_proto_rawDesc)))
	})
	return file_grpc_api_echelon_v1_scanner_proto_rawDescData
}

var file_grpc_api_echelon_v1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_api_echelon_v1_scanner_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: echelon.v1.ScanRequest
	(*ScanResponse)(nil), // 1: echelon.v1.ScanResponse
	(*Finding)(nil),      // 2: echelon.v1.Finding
}
var file_grpc_api_echelon_v1_scanner_proto_depIdxs = []int32{
	2, // 0: echelon.v1.ScanResponse.findings:type_name -> echelon.v1.Finding
	0, // 1: echelon.v1.ScannerService.Scan:input_type -> echelon.v1.ScanRequest
	1, // 2: echelon.v1.ScannerService.Scan:output_type -> echelon.v1.ScanResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_api_echelon_v1_scanner_proto_init() }
func file_grpc_api_echelon_v1_scanner_proto_init() {
	if File_grpc_api_echelon_v1_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_api_echelon_v1_scanner_proto_rawDesc), len(file_grpc_api_echelon_v1_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_api_echelon_v1_scanner_proto_goTypes,
		DependencyIndexes: file_grpc_api_echelon_v1_scanner_proto_depIdxs,
		MessageInfos:      file_grpc_api_echelon_v1_scanner_proto_msgTypes,
	}.Build()
	File_grpc_api_echelon_v1_scanner_proto = out.File
	file_grpc_api_echelon_v1_scanner_proto_goTypes = nil
	file_grpc_api_echelon_v1_scanner_proto_depIdxs = nil
}
